const GAMEBOARD_WIDTH = 1000;
const GAMEBOARD_HEIGHT = 500;
const ORIENTATION_LEFT = "left";
const ORIENTATION_RIGHT = "right";
const NEW_GAME_BG = new Image();
NEW_GAME_BG.src = 'picture/newgame.png';
const BACK_GROUND = new Image();
BACK_GROUND.src = 'picture/background.png';
const TANK_1 = new Image();
TANK_1.src = 'picture/Tank_1right.png';
const TANK_2 = new Image();
TANK_2.src = 'picture/Tank_2left.png';
const EXPLOSIVE = new Image();
EXPLOSIVE.src = 'picture/explosive.png'
const TANK_WIDTH = 70;
const TANK_HEIGHT = 70;
const GRAVITY = 0.5;
const RADIUS = 4;